<a href="https://colab.research.google.com/github/HattaAlvi/LearnPython/blob/main/matrix_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Define matrices
A = np.array([[1, 2, 6], [3, 4, 7], [2, 3, 6]])
B = np.array([[5, 6, 8], [7, 8, 0], [1, 4, 5]])

# Matrix addition
addition_result = A + B

# Matrix subtraction
subtraction_result = A - B

# Matrix multiplication
multiplication_result = np.dot(A, B)

# Transpose of a matrix
transpose_result = np.transpose(A)

# Determinant of a matrix
determinant_result = np.linalg.det(A)

# Inverse of a matrix
inverse_result = np.linalg.inv(A)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nMatrix Addition:")
print(addition_result)
print("\nMatrix Subtraction:")
print(subtraction_result)
print("\nMatrix Multiplication:")
print(multiplication_result)
print("\nTranspose of Matrix A:")
print(transpose_result)
print("\nDeterminant of Matrix A:")
print(determinant_result)
print("\nInverse of Matrix A:")
print(inverse_result)

Matrix A:
[[1 2 6]
 [3 4 7]
 [2 3 6]]

Matrix B:
[[5 6 8]
 [7 8 0]
 [1 4 5]]

Matrix Addition:
[[ 6  8 14]
 [10 12  7]
 [ 3  7 11]]

Matrix Subtraction:
[[-4 -4 -2]
 [-4 -4  7]
 [ 1 -1  1]]

Matrix Multiplication:
[[25 46 38]
 [50 78 59]
 [37 60 46]]

Transpose of Matrix A:
[[1 3 2]
 [2 4 3]
 [6 7 6]]

Determinant of Matrix A:
1.0000000000000002

Inverse of Matrix A:
[[  3.   6. -10.]
 [ -4.  -6.  11.]
 [  1.   1.  -2.]]
