<a href="https://colab.research.google.com/github/HattaAlvi/LearnPython/blob/main/matrix_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Define matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix addition
addition_result = A + B

# Matrix subtraction
subtraction_result = A - B

# Matrix multiplication
multiplication_result = np.dot(A, B)

# Transpose of a matrix
transpose_result = np.transpose(A)

# Determinant of a matrix
determinant_result = np.linalg.det(A)

# Inverse of a matrix
inverse_result = np.linalg.inv(A)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nMatrix Addition:")
print(addition_result)
print("\nMatrix Subtraction:")
print(subtraction_result)
print("\nMatrix Multiplication:")
print(multiplication_result)
print("\nTranspose of Matrix A:")
print(transpose_result)
print("\nDeterminant of Matrix A:")
print(determinant_result)
print("\nInverse of Matrix A:")
print(inverse_result)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Matrix Addition:
[[ 6  8]
 [10 12]]

Matrix Subtraction:
[[-4 -4]
 [-4 -4]]

Matrix Multiplication:
[[19 22]
 [43 50]]

Transpose of Matrix A:
[[1 3]
 [2 4]]

Determinant of Matrix A:
-2.0000000000000004

Inverse of Matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]
